/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./bad-bunny/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#705d00",
        "surface-dim": "#dbdbcf",
        "surface-container-highest": "#e4e3d7",
        "secondary-container": "#c3e8ff",
        "surface-container-lowest": "#ffffff",
        "outline": "#777777",
        "inverse-surface": "#303129",
        "tertiary-fixed": "#ffe16d",
        "primary-container": "#ffdad6",
        "primary-fixed": "#ffdad6",
        "on-error": "#ffffff",
        "surface-tint": "#c00014",
        "secondary-fixed-dim": "#7ad0ff",
        "on-background": "#1b1c15",
        "surface-bright": "#fbfaee",
        "inverse-on-surface": "#f2f1e5",
        "on-secondary-fixed-variant": "#004c69",
        "surface-container-high": "#e9e9dd",
        "primary": "#c00014",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#544600",
        "secondary-fixed": "#c3e8ff",
        "on-secondary-container": "#004c69",
        "outline-variant": "#c6c6c6",
        "on-surface": "#1b1c15",
        "background": "#fbfaee",
        "on-surface-variant": "#474747",
        "on-primary-fixed": "#410002",
        "surface-variant": "#e4e3d7",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#e9c400",
        "surface": "#fbfaee",
        "secondary": "#00668a",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb4ab",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#93000d",
        "on-primary-container": "#93000d",
        "error-container": "#ffdad6",
        "tertiary-container": "#ffe16d",
        "on-secondary-fixed": "#001e2c",
        "on-tertiary-fixed": "#221b00",
        "on-tertiary-container": "#544600",
        "inverse-primary": "#ffb4ab",
        "surface-container": "#efeee3",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f4e8"
      },
      fontFamily: {
        "headline": ["Spline Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
